services:
  grafana-lgtm:
    image: 'grafana/otel-lgtm:latest'
    ports:
      - '3000:3000' # UI

  prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      volumes:
          - ./prometheus.yml:/etc/prometheus/prometheus.yml
      ports:
          - "9090:9090"
      depends_on:
          - otel-collector

  jaeger:
      image: jaegertracing/all-in-one:1.52
      container_name: jaeger
      environment:
          - COLLECTOR_OTLP_ENABLED=true
      ports:
          - "16686:16686"  # UI
          - "14250:14250"  # Collector gRPC (classic)

  otel-collector:
    image: 'otel/opentelemetry-collector-contrib:latest'
    volumes:
      - './otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml:ro'
    ports:
      - '4318:4318'
    depends_on:
        -   jaeger

  greeting-service:
    build:
      context: .
      dockerfile: greeting-service/Dockerfile
    ports:
      - "8082:8082"

  hello-service:
    build:
      context: .
      dockerfile: hello-service/Dockerfile
    ports:
      - "8080:8080"

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "8081:8081"
