services:
  grafana-lgtm:
    image: 'grafana/otel-lgtm:latest'
    ports:
      - '3000:3000' # UI

  otel-collector:
    image: 'otel/opentelemetry-collector-contrib:latest'
    volumes:
      - './otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml:ro'
    ports:
      - '4318:4318'

  greeting-service:
    build:
      context: .
      dockerfile: greeting-service/Dockerfile
    ports:
      - "8082:8082"

  hello-service:
    build:
      context: .
      dockerfile: hello-service/Dockerfile
    ports:
      - "8080:8080"

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "8081:8081"
