receivers:
    otlp:
        protocols:
            grpc:
                endpoint: 0.0.0.0:4317
            http:
                endpoint: 0.0.0.0:4318

exporters:
    debug:
        verbosity: basic # basic, normal, detailed
    file:
        # path: /output/data.json
        path: /dev/null
        format: json
        # Prometheus exporter â€“ scraped by Prometheus
    prometheus:
        endpoint: "0.0.0.0:8889"

    # Send traces to Jaeger via OTLP gRPC
    otlp/jaeger:
        endpoint: jaeger:4317
        tls:
            insecure: true

service:
    pipelines:
        traces:
            receivers: [ otlp ]
            exporters: [ otlp/jaeger, debug, file ]
        metrics:
            receivers: [ otlp ]
            exporters: [ prometheus, debug, file ]
        logs:
            receivers: [ otlp ]
            exporters: [ debug, file ]
